"""Consistent Model Format

Revision ID: 30ed6dde169b
Revises: 85475e8471c0
Create Date: 2023-06-30 16:33:55.214445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ed6dde169b'
down_revision = '85475e8471c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journalentry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=False))
        batch_op.drop_column('body')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=False))
        batch_op.drop_column('tags')
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('journalentry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
