"""Added 'type' to Models

Revision ID: 4a39aa671836
Revises: 30ed6dde169b
Create Date: 2023-06-30 16:58:45.286336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a39aa671836'
down_revision = '30ed6dde169b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
