"""Unique CategoryID

Revision ID: 61edff4f40ef
Revises: 8c6a4f6fe5ab
Create Date: 2023-06-20 12:02:25.129560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61edff4f40ef'
down_revision = '8c6a4f6fe5ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
