"""Added date field to journal entry model

Revision ID: 9e5121302f29
Revises: 74d93d519def
Create Date: 2023-07-05 11:43:32.207158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5121302f29'
down_revision = '74d93d519def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journalentry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journalentry', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
